### POST add product
POST {{host_fn2}}/api/update-product?action=add
Content-Type: "application/json"

{
    "marca": "Soprole",
    "nombreProducto": "Leche Cultivada 1.2L Damasco",
    "precio": 1989,
    "categoria": "b385b7f2-a2d9-4f9f-bccc-e27f54f3a2e2",
    "bodegaId": "6dcb7901-3f4e-41a2-9d07-2e3f4b5c6d7e"
}


### POST update product
POST {{host_fn2}}/api/update-product?action=update
Content-Type: "application/json"

{
    "id": "dee7f24e-425f-4557-a900-bdb3d36131c9",
    "precio": 998
}

###