### GET obtener todas las bodegas
GET {{host_bff}}/api/v1/inventory/warehouses

### GET obtener todos los productos
GET {{host_bff}}/api/v1/inventory/products

### GET obtener producto por id
GET {{host_bff}}/api/v1/inventory/products/30d69194-4353-4709-908c-24d6ad288656

### POST crear nuevo producto
POST {{host_bff}}/api/v1/inventory/products/add
Content-Type: application/json

{
  "marca": "Soprole",
  "nombreProducto": "Yogurt Frutilla 120g",
  "precio": 230,
  "categoria": "b385b7f2-a2d9-4f9f-bccc-e27f54f3a2e2",
  "bodegaId": "6dcb7901-3f4e-41a2-9d07-2e3f4b5c6d7e"
}

### PATCH editar precio de un producto por id
PATCH {{host_bff}}/api/v1/inventory/products/update-price/aa4965d3-c4b1-4202-a5c1-3d432a250dd6
Content-Type: application/json

{
  "precio": 260
}

### DELETE eliminar producto por id
DELETE {{host_bff}}/api/v1/inventory/products/aa4965d3-c4b1-4202-a5c1-3d432a250dd6
