### GET obtener todas las bodegas
GET {{host_bff}}/api/v1/inventory/warehouses

### GET obtener todos los productos
GET {{host_bff}}/api/v1/inventory/products

### GET obtener producto por id
GET {{host_bff}}/api/v1/inventory/products/793a06bb-0f64-4163-bee5-5e35224f64c3

### POST crear nuevo producto
POST {{host_bff}}/api/v1/inventory/products/add
Content-Type: application/json

{
  "marca": "Soprole",
  "nombreProducto": "Yogurt Chirimoya 120g",
  "precio": 420,
  "categoria": "b385b7f2-a2d9-4f9f-bccc-e27f54f3a2e2",
  "bodegaId": "6dcb7901-3f4e-41a2-9d07-2e3f4b5c6d7e"
}

### PATCH editar precio de un producto por id
PATCH {{host_bff}}/api/v1/inventory/products/update-price/3881c68d-cd8a-4b39-b2ef-8e35db10018e
Content-Type: application/json

{
  "precio": 410
}

### DELETE eliminar producto por id
DELETE {{host_bff}}/api/v1/inventory/products/3881c68d-cd8a-4b39-b2ef-8e35db10018e
